### Constants
@host = 192.168.0.55
@user = admin
@password = admin

### Generated test data
@projectId = {{$random.alphabetic(10)}}
@buildTypeId = {{$random.alphabetic(10)}}

### 1. Create project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/projects
Content-Type: application/json
Accept: application/json

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "{{projectId}}",
  "id": "{{projectId}}",
  "copyAllAssociatedSettings": true
}


### 2. Create build configuration
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
  "id": "{{buildTypeId}}",
  "name": "Print hello world",
  "project": {
    "id": "{{projectId}}"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
  "buildType": {
    "id": "{{buildTypeId}}"
  }
}

### 4. Check build status
# @no-cookie-jar
GET http://{{user}}:{{password}}@{{host}}:8111/app/rest/builds/id:{{buildId}}
Accept: application/json

### Tests
* status is 200
* json.status is "SUCCESS"
