name: Deploy frontend

on: workflow_call

# These are approximate steps to illustrate how the frontend pipeline might look
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo Building the frontend \(running unit tests during the build, executing linters\), creating and publishing a Docker image
  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage/pre-prod app
        run: echo Deploying the frontend