name: Teamcity deployment

on: push

jobs:
  # Build backend and deploy to the staging/pre-prod environment
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Build frontend and deploy to the staging/pre-prod environment
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Run API tests after backend and frontend jobs are completed
  automation-api:
    needs: [backend, frontend]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Run UI tests after backend and frontend jobs are completed
  automation-ui:
    needs: [backend, frontend]
    uses: ./.github/workflows/automation.yml
    with:
      package: web

  manual-prod-approval:
    needs: [automation-ui, automation-api]
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Approve backend and frontend to production
        run: echo Release approved

  deploy-prod:
    needs: manual-prod-approval
    runs-on: ubuntu-latest
    # Mock echo run, just to show the final step
    steps:
      - name: Running backend and frontend deployment
        run: echo Deployment started...